### ISSUE TITLE
Try write CSV to XLSX got an error

### ISSUE THREAD

**Issue by marioidival** [360EntSecGroup-Skylar/excelize#122]
```
 go env                                                
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mario/src/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build060412853=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

Error:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/360EntSecGroup-Skylar/excelize.(*File).SetCellStr(0xc420052060, 0x572db7, 0x6, 0xc420013b48, 0x1, 0xc420104000, 0x9)
	/home/mario/src/go/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:385 +0x486
github.com/360EntSecGroup-Skylar/excelize.(*File).SetCellValue(0xc420052060, 0x572db7, 0x6, 0xc420013b48, 0x1, 0x538dc0, 0xc4200f4680)
	/home/mario/src/go/src/github.com/360EntSecGroup-Skylar/excelize/cell.go:59 +0x757
main.main()
	/home/mario/src/go/src/github.com/nuveo/main.go:47 +0x2f8
exit status 2
```

code:
```go
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func main() {

	f, err := os.Open("data/csv_tmp_file.csv")
	if err != nil {
		panic(err.Error())
	}
	defer f.Close()

	var count int
	xlsx := excelize.NewFile()
	// Create a new sheet.
	sc := bufio.NewScanner(f)
	sc.Split(bufio.ScanLines)
	for sc.Scan() {
		if count == 0 {
			headerTextSplited := strings.Split(sc.Text(), ",")
			for i, header := range headerTextSplited {
				fmt.Printf("%s %s\n", excelize.ToAlphaString(i), header)
				xlsx.SetCellValue("Sheet1", excelize.ToAlphaString(i), header)
			}
			count++
			continue
		}

		valuesTextSplited := strings.Split(sc.Text(), ",")
		for i, value := range valuesTextSplited {
			xlsx.SetCellValue("Sheet1", fmt.Sprintf("%s%s", excelize.ToAlphaString(i), count), value)
		}
                count++
	}

	// Save xlsx file by the given path.
	err = xlsx.SaveAs("./teste_excelize.xlsx")
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by xuri** [comment]
Thanks for your issue. Use the correct coordinates in the `SetCellValue()` function, `excelize.ToAlphaString(i)` just defined column but the row number is missing in the above code.
