### ISSUE TITLE
error when get all rows from file 

### ISSUE THREAD

**Issue by PKostya** [360EntSecGroup-Skylar/excelize#188]
when i try to read the file i get the following error
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/360EntSecGroup-Skylar/excelize.(*xlsxC).getValueFrom(0xc08dc65c38, 0xc042088540, 0xc04208a190, 0xc09826c03c, 0x1, 0x0, 0x2)
        C:/Users/adm_Palyanichka/go/src/github.com/360EntSecGroup-Skylar/excelize/rows.go:165 +0x23d
github.com/360EntSecGroup-Skylar/excelize.(*File).GetRows(0xc042088540, 0xc04205e6f8, 0x7, 0x8, 0x0, 0x0)
        C:/Users/adm_Palyanichka/go/src/github.com/360EntSecGroup-Skylar/excelize/rows.go:60 +0x7b8
main.writeFile(0xc04204b440, 0xc04205c120, 0x12)
        C:/Users/adm_Palyanichka/go/src/carmoney.com/xlsx-converter/xlsxConverter.go:26 +0x238
main.main()
        C:/Users/adm_Palyanichka/go/src/carmoney.com/xlsx-converter/xlsxConverter.go:88 +0x210
exit status 2
```

**Output of `go version`:**

```
1.10
```

**Comment by xuri** [comment]
Thanks for your issue. Please provides file attachments if you can.

**Comment by PKostya** [comment]
Hi
[tmp.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/1771643/tmp.xlsx)

**Comment by xuri** [comment]
I have found that the file name of shared string table in your attachment is special: `xl/SharedStrings.xml` (standard filename is `xl/sharedStrings.xml`) and I have fixed it now, Could you tell me which version of Excel that created this file?

**Comment by PKostya** [comment]
This file was created by 1C software (very controversial software)
